print (  " x       y           x and y            x or y          not x          not y")
print ("True    False        ",True and False,"            ",True or False,"         ",not True,"        ",not False,)
print ("False   True         ",False and True,"            ",False or True,"         ",not False,"         ",not True,)
print ("False   False        ",False and False,"            ",False or False,"        ",not False,"         ",not False,)
print ("True    True         ",True and True,"             ",True or True,"         ",not True,"        ",not True,) 
